extends: airbnb
parser: babel-eslint
env:
  es6: true
  browser: true
  node: true
  mocha: true
rules:
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react/prefer-stateless-function: 0
  no-use-before-define: 0
  import/no-extraneous-dependencies: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
  react/prop-types: 0



